<a href="https://colab.research.google.com/github/s104004501/AI/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

In [0]:
import pandas as pd
print("pandas version: %s" % pd.__version__)


In [0]:
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)


# 建立array(陣列)

###使用np.array()建立陣列

In [0]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

###使用numpy提供的創建函數直接生成


In [11]:
import numpy as np
x = np.zeros((2, 3))
print(x)


[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
import numpy as np
y = np.arange(2, 3, 0.1) # start, end, step

print(y)

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [9]:
import numpy as np

z = np.linspace(1., 4., 6) # start, end, num
print(z)

[1.  1.6 2.2 2.8 3.4 4. ]


In [13]:
import numpy as np

z = np.linspace(2.0, 3.0, num=5)

print(z)

[2.   2.25 2.5  2.75 3.  ]


In [14]:
import numpy as np

z = np.linspace(2.0, 3.0, num=5, endpoint=False)

print(z)

[2.  2.2 2.4 2.6 2.8]


In [15]:
import numpy as np

z = np.linspace(2.0, 3.0, num=5, retstep=True)
print(z)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


##屬性

In [0]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

ar2.shape


In [18]:
ar2.ndim


2

##Ndarray的各種運算

###reshape

In [21]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [22]:
x2 = x.reshape(4,1)
x2

array([[0],
       [1],
       [2],
       [3]])

In [23]:
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [24]:
import numpy as np
x = np.arange(2,10).reshape(4,2)
x

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
import numpy as np
x = np.arange(24).reshape(3,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [29]:
import numpy as np
x = np.arange(24).reshape(4,3,2)

x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [30]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 

ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [31]:
ar.ravel()


array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [32]:
ar.T.ravel()


array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [33]:
import numpy as np
ar=np.random.rand(4,2)


ar

array([[0.78215814, 0.50558393],
       [0.06715706, 0.58693079],
       [0.94759818, 0.01609983],
       [0.15229502, 0.61150053]])

In [34]:
import numpy as np
ar=np.random.rand(4,2)


ar

array([[0.92548723, 0.48593118],
       [0.66953531, 0.12706256],
       [0.71537452, 0.60785124],
       [0.19095902, 0.5948434 ]])

In [36]:
import numpy as np
ar=np.random.rand(4,3,2)


ar

array([[[0.77349516, 0.92162982],
        [0.12402755, 0.46674574],
        [0.94377081, 0.97455256]],

       [[0.41116814, 0.29528381],
        [0.96468808, 0.8020305 ],
        [0.48616676, 0.41808065]],

       [[0.78701196, 0.23736284],
        [0.1468998 , 0.66868307],
        [0.90169613, 0.25341794]],

       [[0.76737319, 0.5286602 ],
        [0.05875538, 0.87896293],
        [0.71551691, 0.41748527]]])